{
package main

import (
	"github.com/alecthomas/repr"
)

func slice(v interface{}) []interface{} {
    if v == nil {
        return nil
    }
    return v.([]interface{})
}

type Crumb struct {
    Value string
}
}

QUERY <- vals:(CrumbSeparator Ident)+ EOF {
    repr.Println(vals)
    return &Crumb{Value: slice(slice(vals)[0])[1].(string)}, nil
}

Ident <- val:Char+ {
    return string(c.text), nil
}

Char <- [a-z]

CrumbSeparator <- val:'.' {
    return string(c.text), nil
}

EOF ← !.