// Code generated by pigeon; DO NOT EDIT.

package queryast

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

type Query struct {
	Parts *Expr
}

type Expr struct {
	Node interface{}
	Next interface{}
}

type FunctionCall struct {
	Name   string
	Params interface{}
}

type Path struct {
	Crumbs []*Crumb
}

type Crumb struct {
	Key *Key
}

type EmptySelector struct {
}

func (s *EmptySelector) Accumulate(accum *Accumulation) error {
	return nil
}

type IndexSelector struct {
	Index int
}

type SplatSelector struct {
}

type MapSelector struct {
	Key string
}

type Key struct {
	Ident    string
	Selector interface{}
}

type Accumulation struct {
	Results []interface{}
}

func (a *Accumulation) AddResult(result interface{}) {
	a.Results = append(a.Results, result)
}

type Accumulator interface {
	AddResult() func(a *Accumulator) error
}

var g = &grammar{
	rules: []*rule{
		{
			name: "QUERY",
			pos:  position{line: 71, col: 1, offset: 909},
			expr: &actionExpr{
				pos: position{line: 71, col: 10, offset: 918},
				run: (*parser).callonQUERY1,
				expr: &seqExpr{
					pos: position{line: 71, col: 10, offset: 918},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 71, col: 10, offset: 918},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 71, col: 12, offset: 920},
							label: "exp",
							expr: &ruleRefExpr{
								pos:  position{line: 71, col: 16, offset: 924},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 71, col: 21, offset: 929},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 71, col: 23, offset: 931},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 75, col: 1, offset: 960},
			expr: &actionExpr{
				pos: position{line: 75, col: 9, offset: 968},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 75, col: 9, offset: 968},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 75, col: 9, offset: 968},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 75, col: 15, offset: 974},
								name: "SubExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 75, col: 23, offset: 982},
							label: "rest",
							expr: &zeroOrOneExpr{
								pos: position{line: 75, col: 28, offset: 987},
								expr: &ruleRefExpr{
									pos:  position{line: 75, col: 28, offset: 987},
									name: "NextExpr",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SubExpr",
			pos:  position{line: 80, col: 1, offset: 1070},
			expr: &actionExpr{
				pos: position{line: 80, col: 12, offset: 1081},
				run: (*parser).callonSubExpr1,
				expr: &labeledExpr{
					pos:   position{line: 80, col: 12, offset: 1081},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 80, col: 17, offset: 1086},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 80, col: 17, offset: 1086},
								name: "Path",
							},
							&ruleRefExpr{
								pos:  position{line: 80, col: 24, offset: 1093},
								name: "Function",
							},
						},
					},
				},
			},
		},
		{
			name: "NextExpr",
			pos:  position{line: 84, col: 1, offset: 1128},
			expr: &actionExpr{
				pos: position{line: 84, col: 13, offset: 1140},
				run: (*parser).callonNextExpr1,
				expr: &seqExpr{
					pos: position{line: 84, col: 13, offset: 1140},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 84, col: 13, offset: 1140},
							name: "PipeSeparator",
						},
						&labeledExpr{
							pos:   position{line: 84, col: 27, offset: 1154},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 84, col: 32, offset: 1159},
								name: "Expr",
							},
						},
					},
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 88, col: 1, offset: 1190},
			expr: &actionExpr{
				pos: position{line: 88, col: 13, offset: 1202},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 88, col: 13, offset: 1202},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 88, col: 13, offset: 1202},
							label: "ident",
							expr: &ruleRefExpr{
								pos:  position{line: 88, col: 19, offset: 1208},
								name: "Ident",
							},
						},
						&labeledExpr{
							pos:   position{line: 88, col: 25, offset: 1214},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 88, col: 30, offset: 1219},
								expr: &ruleRefExpr{
									pos:  position{line: 88, col: 30, offset: 1219},
									name: "Params",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Params",
			pos:  position{line: 95, col: 1, offset: 1356},
			expr: &actionExpr{
				pos: position{line: 95, col: 11, offset: 1366},
				run: (*parser).callonParams1,
				expr: &seqExpr{
					pos: position{line: 95, col: 11, offset: 1366},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 95, col: 11, offset: 1366},
							val:        "(",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 95, col: 15, offset: 1370},
							label: "params",
							expr: &zeroOrOneExpr{
								pos: position{line: 95, col: 22, offset: 1377},
								expr: &ruleRefExpr{
									pos:  position{line: 95, col: 22, offset: 1377},
									name: "MultiParam",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 95, col: 34, offset: 1389},
							val:        ")",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "MultiParam",
			pos:  position{line: 99, col: 1, offset: 1421},
			expr: &actionExpr{
				pos: position{line: 99, col: 15, offset: 1435},
				run: (*parser).callonMultiParam1,
				expr: &seqExpr{
					pos: position{line: 99, col: 15, offset: 1435},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 99, col: 15, offset: 1435},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 99, col: 21, offset: 1441},
								name: "SingleParam",
							},
						},
						&labeledExpr{
							pos:   position{line: 99, col: 33, offset: 1453},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 99, col: 38, offset: 1458},
								expr: &ruleRefExpr{
									pos:  position{line: 99, col: 38, offset: 1458},
									name: "NextSingleParam",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "NextSingleParam",
			pos:  position{line: 105, col: 1, offset: 1595},
			expr: &actionExpr{
				pos: position{line: 105, col: 20, offset: 1614},
				run: (*parser).callonNextSingleParam1,
				expr: &seqExpr{
					pos: position{line: 105, col: 20, offset: 1614},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 105, col: 20, offset: 1614},
							val:        ",",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 105, col: 24, offset: 1618},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 105, col: 28, offset: 1622},
								name: "SingleParam",
							},
						},
					},
				},
			},
		},
		{
			name: "SingleParam",
			pos:  position{line: 109, col: 1, offset: 1659},
			expr: &actionExpr{
				pos: position{line: 109, col: 16, offset: 1674},
				run: (*parser).callonSingleParam1,
				expr: &seqExpr{
					pos: position{line: 109, col: 16, offset: 1674},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 109, col: 16, offset: 1674},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 109, col: 18, offset: 1676},
							label: "param",
							expr: &ruleRefExpr{
								pos:  position{line: 109, col: 24, offset: 1682},
								name: "Expr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 109, col: 29, offset: 1687},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Crumb",
			pos:  position{line: 113, col: 1, offset: 1716},
			expr: &actionExpr{
				pos: position{line: 113, col: 10, offset: 1725},
				run: (*parser).callonCrumb1,
				expr: &seqExpr{
					pos: position{line: 113, col: 10, offset: 1725},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 113, col: 10, offset: 1725},
							name: "CrumbSeparator",
						},
						&labeledExpr{
							pos:   position{line: 113, col: 25, offset: 1740},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 113, col: 29, offset: 1744},
								name: "Key",
							},
						},
					},
				},
			},
		},
		{
			name: "Key",
			pos:  position{line: 117, col: 1, offset: 1793},
			expr: &actionExpr{
				pos: position{line: 117, col: 8, offset: 1800},
				run: (*parser).callonKey1,
				expr: &seqExpr{
					pos: position{line: 117, col: 8, offset: 1800},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 117, col: 8, offset: 1800},
							label: "ident",
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 14, offset: 1806},
								name: "Ident",
							},
						},
						&labeledExpr{
							pos:   position{line: 117, col: 20, offset: 1812},
							label: "sel",
							expr: &zeroOrOneExpr{
								pos: position{line: 117, col: 24, offset: 1816},
								expr: &ruleRefExpr{
									pos:  position{line: 117, col: 24, offset: 1816},
									name: "Selector",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Selector",
			pos:  position{line: 121, col: 1, offset: 1888},
			expr: &actionExpr{
				pos: position{line: 121, col: 13, offset: 1900},
				run: (*parser).callonSelector1,
				expr: &seqExpr{
					pos: position{line: 121, col: 13, offset: 1900},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 121, col: 13, offset: 1900},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 121, col: 17, offset: 1904},
							label: "val",
							expr: &zeroOrOneExpr{
								pos: position{line: 121, col: 21, offset: 1908},
								expr: &choiceExpr{
									pos: position{line: 121, col: 22, offset: 1909},
									alternatives: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 121, col: 22, offset: 1909},
											name: "SplatSelector",
										},
										&ruleRefExpr{
											pos:  position{line: 121, col: 38, offset: 1925},
											name: "IndexSelector",
										},
										&ruleRefExpr{
											pos:  position{line: 121, col: 54, offset: 1941},
											name: "MapSelector",
										},
										&ruleRefExpr{
											pos:  position{line: 121, col: 68, offset: 1955},
											name: "EmptySelector",
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 121, col: 85, offset: 1972},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "SplatSelector",
			pos:  position{line: 125, col: 1, offset: 2001},
			expr: &actionExpr{
				pos: position{line: 125, col: 18, offset: 2018},
				run: (*parser).callonSplatSelector1,
				expr: &litMatcher{
					pos:        position{line: 125, col: 18, offset: 2018},
					val:        "*",
					ignoreCase: false,
				},
			},
		},
		{
			name: "IndexSelector",
			pos:  position{line: 129, col: 1, offset: 2060},
			expr: &actionExpr{
				pos: position{line: 129, col: 18, offset: 2077},
				run: (*parser).callonIndexSelector1,
				expr: &labeledExpr{
					pos:   position{line: 129, col: 18, offset: 2077},
					label: "val",
					expr: &ruleRefExpr{
						pos:  position{line: 129, col: 22, offset: 2081},
						name: "Int",
					},
				},
			},
		},
		{
			name: "MapSelector",
			pos:  position{line: 133, col: 1, offset: 2139},
			expr: &actionExpr{
				pos: position{line: 133, col: 16, offset: 2154},
				run: (*parser).callonMapSelector1,
				expr: &labeledExpr{
					pos:   position{line: 133, col: 16, offset: 2154},
					label: "val",
					expr: &ruleRefExpr{
						pos:  position{line: 133, col: 20, offset: 2158},
						name: "Ident",
					},
				},
			},
		},
		{
			name: "EmptySelector",
			pos:  position{line: 137, col: 1, offset: 2217},
			expr: &actionExpr{
				pos: position{line: 137, col: 18, offset: 2234},
				run: (*parser).callonEmptySelector1,
				expr: &ruleRefExpr{
					pos:  position{line: 137, col: 18, offset: 2234},
					name: "_",
				},
			},
		},
		{
			name: "Path",
			pos:  position{line: 141, col: 1, offset: 2274},
			expr: &actionExpr{
				pos: position{line: 141, col: 9, offset: 2282},
				run: (*parser).callonPath1,
				expr: &labeledExpr{
					pos:   position{line: 141, col: 9, offset: 2282},
					label: "vals",
					expr: &oneOrMoreExpr{
						pos: position{line: 141, col: 14, offset: 2287},
						expr: &ruleRefExpr{
							pos:  position{line: 141, col: 14, offset: 2287},
							name: "Crumb",
						},
					},
				},
			},
		},
		{
			name: "Ident",
			pos:  position{line: 153, col: 1, offset: 2584},
			expr: &actionExpr{
				pos: position{line: 153, col: 10, offset: 2593},
				run: (*parser).callonIdent1,
				expr: &labeledExpr{
					pos:   position{line: 153, col: 10, offset: 2593},
					label: "val",
					expr: &oneOrMoreExpr{
						pos: position{line: 153, col: 14, offset: 2597},
						expr: &ruleRefExpr{
							pos:  position{line: 153, col: 14, offset: 2597},
							name: "Char",
						},
					},
				},
			},
		},
		{
			name:        "Char",
			displayName: "\"unicode ident char\"",
			pos:         position{line: 157, col: 1, offset: 2639},
			expr: &charClassMatcher{
				pos:        position{line: 157, col: 30, offset: 2668},
				val:        "[\\x2D\\x5F\\x30-\\x39\\x41-\\x5A\\x61-\\x7A\\xA1-\\u10FFFF]",
				chars:      []rune{'-', '_', 'F', 'F'},
				ranges:     []rune{'0', '9', 'A', 'Z', 'a', 'z', '¡', 'ჿ'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Int",
			pos:  position{line: 159, col: 1, offset: 2720},
			expr: &actionExpr{
				pos: position{line: 159, col: 8, offset: 2727},
				run: (*parser).callonInt1,
				expr: &seqExpr{
					pos: position{line: 159, col: 8, offset: 2727},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 159, col: 8, offset: 2727},
							expr: &litMatcher{
								pos:        position{line: 159, col: 8, offset: 2727},
								val:        "-",
								ignoreCase: false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 159, col: 13, offset: 2732},
							expr: &ruleRefExpr{
								pos:  position{line: 159, col: 13, offset: 2732},
								name: "DecimalDigit",
							},
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 163, col: 1, offset: 2791},
			expr: &charClassMatcher{
				pos:        position{line: 163, col: 17, offset: 2807},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "CrumbSeparator",
			pos:  position{line: 165, col: 1, offset: 2814},
			expr: &actionExpr{
				pos: position{line: 165, col: 19, offset: 2832},
				run: (*parser).callonCrumbSeparator1,
				expr: &litMatcher{
					pos:        position{line: 165, col: 19, offset: 2832},
					val:        ".",
					ignoreCase: false,
				},
			},
		},
		{
			name: "PipeSeparator",
			pos:  position{line: 169, col: 1, offset: 2861},
			expr: &actionExpr{
				pos: position{line: 169, col: 18, offset: 2878},
				run: (*parser).callonPipeSeparator1,
				expr: &seqExpr{
					pos: position{line: 169, col: 18, offset: 2878},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 169, col: 18, offset: 2878},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 169, col: 20, offset: 2880},
							val:        "|",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 169, col: 24, offset: 2884},
							name: "_",
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 173, col: 1, offset: 2911},
			expr: &actionExpr{
				pos: position{line: 173, col: 19, offset: 2929},
				run: (*parser).callon_1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 173, col: 19, offset: 2929},
					expr: &charClassMatcher{
						pos:        position{line: 173, col: 19, offset: 2929},
						val:        "[ \\t\\r\\n]",
						chars:      []rune{' ', '\t', '\r', '\n'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
	},
}

func (c *current) onQUERY1(exp interface{}) (interface{}, error) {
	return exp, nil
}

func (p *parser) callonQUERY1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQUERY1(stack["exp"])
}

func (c *current) onExpr1(first, rest interface{}) (interface{}, error) {
	result := &Expr{Node: first, Next: rest}
	return result, nil
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["first"], stack["rest"])
}

func (c *current) onSubExpr1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonSubExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSubExpr1(stack["val"])
}

func (c *current) onNextExpr1(expr interface{}) (interface{}, error) {
	return expr, nil
}

func (p *parser) callonNextExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNextExpr1(stack["expr"])
}

func (c *current) onFunction1(ident, args interface{}) (interface{}, error) {
	if args == nil {
		args = []interface{}{}
	}
	return &FunctionCall{Name: ident.(string), Params: args}, nil
}

func (p *parser) callonFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["ident"], stack["args"])
}

func (c *current) onParams1(params interface{}) (interface{}, error) {
	return params, nil
}

func (p *parser) callonParams1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onParams1(stack["params"])
}

func (c *current) onMultiParam1(first, rest interface{}) (interface{}, error) {
	results := []interface{}{first}
	results = append(results, rest.([]interface{})...)
	return results, nil
}

func (p *parser) callonMultiParam1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMultiParam1(stack["first"], stack["rest"])
}

func (c *current) onNextSingleParam1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonNextSingleParam1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNextSingleParam1(stack["val"])
}

func (c *current) onSingleParam1(param interface{}) (interface{}, error) {
	return param, nil
}

func (p *parser) callonSingleParam1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleParam1(stack["param"])
}

func (c *current) onCrumb1(key interface{}) (interface{}, error) {
	return &Crumb{Key: key.(*Key)}, nil
}

func (p *parser) callonCrumb1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCrumb1(stack["key"])
}

func (c *current) onKey1(ident, sel interface{}) (interface{}, error) {
	return &Key{Ident: ident.(string), Selector: sel}, nil
}

func (p *parser) callonKey1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKey1(stack["ident"], stack["sel"])
}

func (c *current) onSelector1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelector1(stack["val"])
}

func (c *current) onSplatSelector1() (interface{}, error) {
	return &SplatSelector{}, nil
}

func (p *parser) callonSplatSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSplatSelector1()
}

func (c *current) onIndexSelector1(val interface{}) (interface{}, error) {
	return &IndexSelector{Index: val.(int)}, nil
}

func (p *parser) callonIndexSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIndexSelector1(stack["val"])
}

func (c *current) onMapSelector1(val interface{}) (interface{}, error) {
	return &MapSelector{Key: val.(string)}, nil
}

func (p *parser) callonMapSelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMapSelector1(stack["val"])
}

func (c *current) onEmptySelector1() (interface{}, error) {
	return &EmptySelector{}, nil
}

func (p *parser) callonEmptySelector1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmptySelector1()
}

func (c *current) onPath1(vals interface{}) (interface{}, error) {
	crumbs := []*Crumb{}
	for _, v := range vals.([]interface{}) {
		crumb, ok := v.(*Crumb)
		if !ok {
			return nil, fmt.Errorf("invalid type, expected type *Crumb")
		}
		crumbs = append(crumbs, crumb)
	}
	return &Path{Crumbs: crumbs}, nil
}

func (p *parser) callonPath1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPath1(stack["vals"])
}

func (c *current) onIdent1(val interface{}) (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonIdent1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdent1(stack["val"])
}

func (c *current) onInt1() (interface{}, error) {
	return strconv.Atoi(string(c.text))
}

func (p *parser) callonInt1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInt1()
}

func (c *current) onCrumbSeparator1() (interface{}, error) {
	return nil, nil
}

func (p *parser) callonCrumbSeparator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCrumbSeparator1()
}

func (c *current) onPipeSeparator1() (interface{}, error) {
	return nil, nil
}

func (p *parser) callonPipeSeparator1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPipeSeparator1()
}

func (c *current) on_1() (interface{}, error) {
	return nil, nil
}

func (p *parser) callon_1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.on_1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
